# Generated by Django 5.1 on 2025-05-04 05:44

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='requesttype',
            options={'ordering': ['name'], 'verbose_name': 'Тип заявки', 'verbose_name_plural': 'Типы заявок'},
        ),
        migrations.RemoveField(
            model_name='request',
            name='history',
        ),
        migrations.AlterField(
            model_name='request',
            name='actual_address',
            field=models.TextField(verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='approved_amount_chairman',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма, одобренная председателем'),
        ),
        migrations.AlterField(
            model_name='request',
            name='approved_amount_director',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма, одобренная директором'),
        ),
        migrations.AlterField(
            model_name='request',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', verbose_name='Приложения'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(verbose_name='Описание ситуации / комментарий'),
        ),
        migrations.AlterField(
            model_name='request',
            name='full_name_or_org',
            field=models.CharField(max_length=255, verbose_name='ФИО или название учреждения'),
        ),
        migrations.AlterField(
            model_name='request',
            name='incoming_letter',
            field=models.FileField(blank=True, null=True, upload_to='letters/', verbose_name='Входящее письмо'),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='request',
            name='registration_address',
            field=models.TextField(verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.requesttype', verbose_name='Тип заявки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='requested_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Запрашиваемая сумма'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новый'), ('specialist_review', 'На проверке у специалиста'), ('approved_by_specialist', 'Одобрено специалистом'), ('director_review', 'На рассмотрении у Генерального директора'), ('rejected_by_director', 'Отклонено директором'), ('approved_by_director', 'Одобрено директором'), ('chairman_review', 'На рассмотрении у председателя'), ('rejected_by_chairman', 'Отклонено председателем'), ('approved_by_chairman', 'Одобрено председателем'), ('awaiting_payment', 'Ожидает выплаты'), ('paid', 'Выплачено'), ('payment_pending', 'Выплата в ожидании')], default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='subject_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('organization', 'Юридическое лицо')], max_length=20, verbose_name='Тип субъекта'),
        ),
        migrations.AlterField(
            model_name='request',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название типа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
        migrations.CreateModel(
            name='HistoricalRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('individual', 'Физическое лицо'), ('organization', 'Юридическое лицо')], max_length=20, verbose_name='Тип субъекта')),
                ('full_name_or_org', models.CharField(max_length=255, verbose_name='ФИО или название учреждения')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('actual_address', models.TextField(verbose_name='Фактический адрес')),
                ('registration_address', models.TextField(verbose_name='Адрес прописки')),
                ('description', models.TextField(verbose_name='Описание ситуации / комментарий')),
                ('incoming_letter', models.TextField(blank=True, max_length=100, null=True, verbose_name='Входящее письмо')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Запрашиваемая сумма')),
                ('approved_amount_director', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма, одобренная директором')),
                ('approved_amount_chairman', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сумма, одобренная председателем')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('specialist_review', 'На проверке у специалиста'), ('approved_by_specialist', 'Одобрено специалистом'), ('director_review', 'На рассмотрении у Генерального директора'), ('rejected_by_director', 'Отклонено директором'), ('approved_by_director', 'Одобрено директором'), ('chairman_review', 'На рассмотрении у председателя'), ('rejected_by_chairman', 'Отклонено председателем'), ('approved_by_chairman', 'Одобрено председателем'), ('awaiting_payment', 'Ожидает выплаты'), ('paid', 'Выплачено'), ('payment_pending', 'Выплата в ожидании')], default='new', max_length=50, verbose_name='Статус')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата подачи')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления')),
                ('attachments', models.TextField(blank=True, max_length=100, null=True, verbose_name='Приложения')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('request_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='crm.requesttype', verbose_name='Тип заявки')),
            ],
            options={
                'verbose_name': 'historical Заявка',
                'verbose_name_plural': 'historical Заявки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
