# Generated by Django 5.1 on 2025-05-04 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_request_options_alter_requesttype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequest',
            name='actual_address',
            field=models.CharField(max_length=255, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='registration_address',
            field=models.CharField(max_length=255, verbose_name='Адрес прописки'),
        ),
        migrations.AlterField(
            model_name='request',
            name='actual_address',
            field=models.CharField(max_length=255, verbose_name='Фактический адрес'),
        ),
        migrations.AlterField(
            model_name='request',
            name='registration_address',
            field=models.CharField(max_length=255, verbose_name='Адрес прописки'),
        ),
    ]
