# Generated by Django 5.1 on 2025-05-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_alter_historicalrequest_actual_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequest',
            name='requisites',
            field=models.CharField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AddField(
            model_name='request',
            name='requisites',
            field=models.CharField(blank=True, null=True, verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='historicalrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved_by_specialist', 'Одобрено специалистом'), ('rejected_by_specialist', 'Отклонено специалистом'), ('approved_by_director', 'Одобрено директором'), ('rejected_by_director', 'Отклонено директором'), ('sent_to_chairman', 'Направлено председателю'), ('approved_by_chairman', 'Одобрено председателем'), ('rejected_by_chairman', 'Отклонено председателем'), ('awaiting_payment', 'Ожидает выплаты'), ('paid', 'Выплачено')], default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved_by_specialist', 'Одобрено специалистом'), ('rejected_by_specialist', 'Отклонено специалистом'), ('approved_by_director', 'Одобрено директором'), ('rejected_by_director', 'Отклонено директором'), ('sent_to_chairman', 'Направлено председателю'), ('approved_by_chairman', 'Одобрено председателем'), ('rejected_by_chairman', 'Отклонено председателем'), ('awaiting_payment', 'Ожидает выплаты'), ('paid', 'Выплачено')], default='new', max_length=50, verbose_name='Статус'),
        ),
    ]
