# Generated by Django 5.1 on 2025-05-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_historicalrequest_requisites_request_requisites_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tg_chat_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telegram Chat ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='tg_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон Telegram'),
        ),
    ]
