# Generated by Django 5.1 on 2025-07-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_user_tg_chat_id_user_tg_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequest',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved_by_specialist', 'Одобрено специалистом'), ('rejected_by_specialist', 'Отклонено специалистом'), ('approved_by_director', 'Одобрено директором'), ('rejected_by_director', 'Отклонено директором'), ('sent_to_chairman', 'Направлено председателю'), ('approved_by_chairman', 'Одобрено председателем'), ('rejected_by_chairman', 'Отклонено председателем'), ('awaiting_payment', 'Ожидает выплаты'), ('paid', 'Выплачено')], db_index=True, default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('approved_by_specialist', 'Одобрено специалистом'), ('rejected_by_specialist', 'Отклонено специалистом'), ('approved_by_director', 'Одобрено директором'), ('rejected_by_director', 'Отклонено директором'), ('sent_to_chairman', 'Направлено председателю'), ('approved_by_chairman', 'Одобрено председателем'), ('rejected_by_chairman', 'Отклонено председателем'), ('awaiting_payment', 'Ожидает выплаты'), ('paid', 'Выплачено')], db_index=True, default='new', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tg_phone_number',
            field=models.CharField(blank=True, help_text='Заполните без +, например: 996111222333', max_length=20, null=True, verbose_name='Телефон Telegram'),
        ),
    ]
